# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PW_DATA\rnd\pw_RATconverter\ratConvert.ui'
#
# Created: Fri May 06 20:04:16 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ratWindow(object):
    def setupUi(self, ratWindow):
        ratWindow.setObjectName("ratWindow")
        ratWindow.resize(508, 440)
        ratWindow.setMaximumSize(QtCore.QSize(16777215, 1000000))
        self.centralwidget = QtGui.QWidget(ratWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iconvertgrp = QtGui.QGroupBox(self.centralwidget)
        self.iconvertgrp.setObjectName("iconvertgrp")
        self.horizontalLayout = QtGui.QHBoxLayout(self.iconvertgrp)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconvert_lb = QtGui.QLabel(self.iconvertgrp)
        self.iconvert_lb.setObjectName("iconvert_lb")
        self.horizontalLayout.addWidget(self.iconvert_lb)
        self.browsIconvert_btn = QtGui.QPushButton(self.iconvertgrp)
        self.browsIconvert_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browsIconvert_btn.setObjectName("browsIconvert_btn")
        self.horizontalLayout.addWidget(self.browsIconvert_btn)
        self.verticalLayout_3.addWidget(self.iconvertgrp)
        self.path_grp = QtGui.QGroupBox(self.centralwidget)
        self.path_grp.setObjectName("path_grp")
        self.gridLayout = QtGui.QGridLayout(self.path_grp)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.sub_cb = QtGui.QCheckBox(self.path_grp)
        self.sub_cb.setChecked(True)
        self.sub_cb.setObjectName("sub_cb")
        self.gridLayout.addWidget(self.sub_cb, 4, 0, 1, 1)
        self.source_ly = QtGui.QHBoxLayout()
        self.source_ly.setContentsMargins(-1, 0, -1, -1)
        self.source_ly.setObjectName("source_ly")
        self.sourceList_lw = QtGui.QListWidget(self.path_grp)
        self.sourceList_lw.setObjectName("sourceList_lw")
        self.source_ly.addWidget(self.sourceList_lw)
        self.gridLayout.addLayout(self.source_ly, 0, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.browseFolder_btn = QtGui.QPushButton(self.path_grp)
        self.browseFolder_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseFolder_btn.setObjectName("browseFolder_btn")
        self.verticalLayout_5.addWidget(self.browseFolder_btn)
        self.browseFiles_btn = QtGui.QPushButton(self.path_grp)
        self.browseFiles_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseFiles_btn.setObjectName("browseFiles_btn")
        self.verticalLayout_5.addWidget(self.browseFiles_btn)
        self.remove_btn = QtGui.QPushButton(self.path_grp)
        self.remove_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_5.addWidget(self.remove_btn)
        self.show_btn = QtGui.QPushButton(self.path_grp)
        self.show_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.show_btn.setCheckable(True)
        self.show_btn.setChecked(True)
        self.show_btn.setObjectName("show_btn")
        self.verticalLayout_5.addWidget(self.show_btn)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.path_grp)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.browseTarget_btn = QtGui.QPushButton(self.groupBox)
        self.browseTarget_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseTarget_btn.setObjectName("browseTarget_btn")
        self.gridLayout_2.addWidget(self.browseTarget_btn, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.format_cb = QtGui.QComboBox(self.groupBox)
        self.format_cb.setObjectName("format_cb")
        self.horizontalLayout_3.addWidget(self.format_cb)
        self.over_rb = QtGui.QRadioButton(self.groupBox)
        self.over_rb.setChecked(True)
        self.over_rb.setObjectName("over_rb")
        self.horizontalLayout_3.addWidget(self.over_rb)
        self.skip_rb = QtGui.QRadioButton(self.groupBox)
        self.skip_rb.setObjectName("skip_rb")
        self.horizontalLayout_3.addWidget(self.skip_rb)
        self.ask_rb = QtGui.QRadioButton(self.groupBox)
        self.ask_rb.setObjectName("ask_rb")
        self.horizontalLayout_3.addWidget(self.ask_rb)
        self.autoRename_rb = QtGui.QRadioButton(self.groupBox)
        self.autoRename_rb.setObjectName("autoRename_rb")
        self.horizontalLayout_3.addWidget(self.autoRename_rb)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 3)
        self.newtarget_ly = QtGui.QHBoxLayout()
        self.newtarget_ly.setContentsMargins(0, -1, -1, -1)
        self.newtarget_ly.setObjectName("newtarget_ly")
        self.target_le = QtGui.QLineEdit(self.groupBox)
        self.target_le.setText("")
        self.target_le.setObjectName("target_le")
        self.newtarget_ly.addWidget(self.target_le)
        self.gridLayout_2.addLayout(self.newtarget_ly, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RAT_btn = QtGui.QPushButton(self.centralwidget)
        self.RAT_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.RAT_btn.setObjectName("RAT_btn")
        self.horizontalLayout_2.addWidget(self.RAT_btn)
        self.multi_cb = QtGui.QCheckBox(self.centralwidget)
        self.multi_cb.setEnabled(False)
        self.multi_cb.setObjectName("multi_cb")
        self.horizontalLayout_2.addWidget(self.multi_cb)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.ext_grp = QtGui.QGroupBox(self.centralwidget)
        self.ext_grp.setMinimumSize(QtCore.QSize(130, 0))
        self.ext_grp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ext_grp.setObjectName("ext_grp")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ext_grp)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newExt_le = QtGui.QLineEdit(self.ext_grp)
        self.newExt_le.setObjectName("newExt_le")
        self.verticalLayout_2.addWidget(self.newExt_le)
        self.scrollArea = QtGui.QScrollArea(self.ext_grp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 116, 281))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.extList_lw = QtGui.QListWidget(self.scrollAreaWidgetContents)
        self.extList_lw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.extList_lw.setObjectName("extList_lw")
        self.verticalLayout.addWidget(self.extList_lw)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkAll_btn = QtGui.QPushButton(self.ext_grp)
        self.checkAll_btn.setMaximumSize(QtCore.QSize(16777215, 17))
        self.checkAll_btn.setObjectName("checkAll_btn")
        self.horizontalLayout_6.addWidget(self.checkAll_btn)
        self.unckeckAll_btn = QtGui.QPushButton(self.ext_grp)
        self.unckeckAll_btn.setMaximumSize(QtCore.QSize(16777215, 17))
        self.unckeckAll_btn.setText("")
        self.unckeckAll_btn.setObjectName("unckeckAll_btn")
        self.horizontalLayout_6.addWidget(self.unckeckAll_btn)
        self.delExt_btn = QtGui.QPushButton(self.ext_grp)
        self.delExt_btn.setMinimumSize(QtCore.QSize(0, 15))
        self.delExt_btn.setMaximumSize(QtCore.QSize(16777215, 17))
        self.delExt_btn.setObjectName("delExt_btn")
        self.horizontalLayout_6.addWidget(self.delExt_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addWidget(self.ext_grp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.progress_bar = QtGui.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_7.addWidget(self.progress_bar)
        self.stop_btn = QtGui.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_7.addWidget(self.stop_btn)
        self.help_btn = QtGui.QPushButton(self.centralwidget)
        self.help_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.help_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout_7.addWidget(self.help_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        ratWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(ratWindow)
        self.statusBar.setObjectName("statusBar")
        ratWindow.setStatusBar(self.statusBar)

        self.retranslateUi(ratWindow)
        QtCore.QMetaObject.connectSlotsByName(ratWindow)
        ratWindow.setTabOrder(self.newExt_le, self.over_rb)
        ratWindow.setTabOrder(self.over_rb, self.skip_rb)
        ratWindow.setTabOrder(self.skip_rb, self.ask_rb)
        ratWindow.setTabOrder(self.ask_rb, self.browsIconvert_btn)
        ratWindow.setTabOrder(self.browsIconvert_btn, self.browseTarget_btn)
        ratWindow.setTabOrder(self.browseTarget_btn, self.scrollArea)
        ratWindow.setTabOrder(self.scrollArea, self.extList_lw)
        ratWindow.setTabOrder(self.extList_lw, self.checkAll_btn)
        ratWindow.setTabOrder(self.checkAll_btn, self.unckeckAll_btn)
        ratWindow.setTabOrder(self.unckeckAll_btn, self.delExt_btn)
        ratWindow.setTabOrder(self.delExt_btn, self.stop_btn)
        ratWindow.setTabOrder(self.stop_btn, self.help_btn)
        ratWindow.setTabOrder(self.help_btn, self.RAT_btn)

    def retranslateUi(self, ratWindow):
        ratWindow.setWindowTitle(QtGui.QApplication.translate("ratWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.iconvertgrp.setTitle(QtGui.QApplication.translate("ratWindow", "iConvert", None, QtGui.QApplication.UnicodeUTF8))
        self.iconvert_lb.setText(QtGui.QApplication.translate("ratWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.browsIconvert_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Select iconvert dinary", None, QtGui.QApplication.UnicodeUTF8))
        self.browsIconvert_btn.setText(QtGui.QApplication.translate("ratWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.path_grp.setTitle(QtGui.QApplication.translate("ratWindow", "Source dir or files", None, QtGui.QApplication.UnicodeUTF8))
        self.sub_cb.setText(QtGui.QApplication.translate("ratWindow", "Include subfolder", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFolder_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Select folder to convert", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFolder_btn.setText(QtGui.QApplication.translate("ratWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFiles_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Select files to convert</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFiles_btn.setText(QtGui.QApplication.translate("ratWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Remove line</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.remove_btn.setText(QtGui.QApplication.translate("ratWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.show_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Show\\hide full path</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.show_btn.setText(QtGui.QApplication.translate("ratWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ratWindow", "Out dir", None, QtGui.QApplication.UnicodeUTF8))
        self.browseTarget_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Select output folder", None, QtGui.QApplication.UnicodeUTF8))
        self.browseTarget_btn.setText(QtGui.QApplication.translate("ratWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.over_rb.setText(QtGui.QApplication.translate("ratWindow", "replace", None, QtGui.QApplication.UnicodeUTF8))
        self.skip_rb.setText(QtGui.QApplication.translate("ratWindow", "skip", None, QtGui.QApplication.UnicodeUTF8))
        self.ask_rb.setText(QtGui.QApplication.translate("ratWindow", "ask", None, QtGui.QApplication.UnicodeUTF8))
        self.autoRename_rb.setText(QtGui.QApplication.translate("ratWindow", "auto", None, QtGui.QApplication.UnicodeUTF8))
        self.target_le.setToolTip(QtGui.QApplication.translate("ratWindow", "Leave empty to use the original folder", None, QtGui.QApplication.UnicodeUTF8))
        self.RAT_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Start Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.RAT_btn.setText(QtGui.QApplication.translate("ratWindow", "START !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.multi_cb.setText(QtGui.QApplication.translate("ratWindow", "MT", None, QtGui.QApplication.UnicodeUTF8))
        self.ext_grp.setTitle(QtGui.QApplication.translate("ratWindow", "   Ext list", None, QtGui.QApplication.UnicodeUTF8))
        self.newExt_le.setToolTip(QtGui.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter extension and press Return</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">For example:<span style=\" font-weight:600;\"> jpg</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">If extension already exists, text ignored</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.extList_lw.setToolTip(QtGui.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uncheck for skip file type</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAll_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Select all", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAll_btn.setText(QtGui.QApplication.translate("ratWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.unckeckAll_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Unselect all", None, QtGui.QApplication.UnicodeUTF8))
        self.delExt_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Delete Ext", None, QtGui.QApplication.UnicodeUTF8))
        self.delExt_btn.setText(QtGui.QApplication.translate("ratWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Stop process", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_btn.setText(QtGui.QApplication.translate("ratWindow", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.help_btn.setToolTip(QtGui.QApplication.translate("ratWindow", "Show help", None, QtGui.QApplication.UnicodeUTF8))
        self.help_btn.setText(QtGui.QApplication.translate("ratWindow", "?", None, QtGui.QApplication.UnicodeUTF8))

