# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\work\pw_RATconverter\RATconverter\ratConvert.ui',
# licensing of 'D:\work\pw_RATconverter\RATconverter\ratConvert.ui' applies.
#
# Created: Tue Oct  6 13:13:02 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_ratWindow(object):
    def setupUi(self, ratWindow):
        ratWindow.setObjectName("ratWindow")
        ratWindow.resize(508, 440)
        ratWindow.setMaximumSize(QtCore.QSize(16777215, 1000000))
        self.centralwidget = QtWidgets.QWidget(ratWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iconvertgrp = QtWidgets.QGroupBox(self.centralwidget)
        self.iconvertgrp.setObjectName("iconvertgrp")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.iconvertgrp)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iconvert_lb = QtWidgets.QLabel(self.iconvertgrp)
        self.iconvert_lb.setObjectName("iconvert_lb")
        self.horizontalLayout.addWidget(self.iconvert_lb)
        self.browsIconvert_btn = QtWidgets.QPushButton(self.iconvertgrp)
        self.browsIconvert_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browsIconvert_btn.setObjectName("browsIconvert_btn")
        self.horizontalLayout.addWidget(self.browsIconvert_btn)
        self.verticalLayout_3.addWidget(self.iconvertgrp)
        self.path_grp = QtWidgets.QGroupBox(self.centralwidget)
        self.path_grp.setObjectName("path_grp")
        self.gridLayout = QtWidgets.QGridLayout(self.path_grp)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.sub_cb = QtWidgets.QCheckBox(self.path_grp)
        self.sub_cb.setChecked(True)
        self.sub_cb.setObjectName("sub_cb")
        self.gridLayout.addWidget(self.sub_cb, 4, 0, 1, 1)
        self.source_ly = QtWidgets.QHBoxLayout()
        self.source_ly.setContentsMargins(-1, 0, -1, -1)
        self.source_ly.setObjectName("source_ly")
        self.sourceList_lw = QtWidgets.QListWidget(self.path_grp)
        self.sourceList_lw.setObjectName("sourceList_lw")
        self.source_ly.addWidget(self.sourceList_lw)
        self.gridLayout.addLayout(self.source_ly, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.browseFolder_btn = QtWidgets.QPushButton(self.path_grp)
        self.browseFolder_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseFolder_btn.setObjectName("browseFolder_btn")
        self.verticalLayout_5.addWidget(self.browseFolder_btn)
        self.browseFiles_btn = QtWidgets.QPushButton(self.path_grp)
        self.browseFiles_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseFiles_btn.setObjectName("browseFiles_btn")
        self.verticalLayout_5.addWidget(self.browseFiles_btn)
        self.remove_btn = QtWidgets.QPushButton(self.path_grp)
        self.remove_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.remove_btn.setObjectName("remove_btn")
        self.verticalLayout_5.addWidget(self.remove_btn)
        self.show_btn = QtWidgets.QPushButton(self.path_grp)
        self.show_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.show_btn.setCheckable(True)
        self.show_btn.setChecked(True)
        self.show_btn.setObjectName("show_btn")
        self.verticalLayout_5.addWidget(self.show_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.path_grp)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.browseTarget_btn = QtWidgets.QPushButton(self.groupBox)
        self.browseTarget_btn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browseTarget_btn.setObjectName("browseTarget_btn")
        self.gridLayout_2.addWidget(self.browseTarget_btn, 0, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.format_cb = QtWidgets.QComboBox(self.groupBox)
        self.format_cb.setObjectName("format_cb")
        self.horizontalLayout_3.addWidget(self.format_cb)
        self.over_rb = QtWidgets.QRadioButton(self.groupBox)
        self.over_rb.setChecked(True)
        self.over_rb.setObjectName("over_rb")
        self.horizontalLayout_3.addWidget(self.over_rb)
        self.skip_rb = QtWidgets.QRadioButton(self.groupBox)
        self.skip_rb.setObjectName("skip_rb")
        self.horizontalLayout_3.addWidget(self.skip_rb)
        self.ask_rb = QtWidgets.QRadioButton(self.groupBox)
        self.ask_rb.setObjectName("ask_rb")
        self.horizontalLayout_3.addWidget(self.ask_rb)
        self.autoRename_rb = QtWidgets.QRadioButton(self.groupBox)
        self.autoRename_rb.setObjectName("autoRename_rb")
        self.horizontalLayout_3.addWidget(self.autoRename_rb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 3)
        self.newtarget_ly = QtWidgets.QHBoxLayout()
        self.newtarget_ly.setContentsMargins(0, -1, -1, -1)
        self.newtarget_ly.setObjectName("newtarget_ly")
        self.target_le = QtWidgets.QLineEdit(self.groupBox)
        self.target_le.setText("")
        self.target_le.setObjectName("target_le")
        self.newtarget_ly.addWidget(self.target_le)
        self.gridLayout_2.addLayout(self.newtarget_ly, 0, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.RAT_btn = QtWidgets.QPushButton(self.centralwidget)
        self.RAT_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.RAT_btn.setObjectName("RAT_btn")
        self.horizontalLayout_2.addWidget(self.RAT_btn)
        self.multi_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.multi_cb.setEnabled(False)
        self.multi_cb.setObjectName("multi_cb")
        self.horizontalLayout_2.addWidget(self.multi_cb)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.ext_grp = QtWidgets.QGroupBox(self.centralwidget)
        self.ext_grp.setMinimumSize(QtCore.QSize(130, 0))
        self.ext_grp.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ext_grp.setObjectName("ext_grp")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.ext_grp)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.newExt_le = QtWidgets.QLineEdit(self.ext_grp)
        self.newExt_le.setObjectName("newExt_le")
        self.verticalLayout_2.addWidget(self.newExt_le)
        self.scrollArea = QtWidgets.QScrollArea(self.ext_grp)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 116, 281))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.extList_lw = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.extList_lw.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.extList_lw.setObjectName("extList_lw")
        self.verticalLayout.addWidget(self.extList_lw)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkAll_btn = QtWidgets.QPushButton(self.ext_grp)
        self.checkAll_btn.setMaximumSize(QtCore.QSize(16777215, 17))
        self.checkAll_btn.setObjectName("checkAll_btn")
        self.horizontalLayout_6.addWidget(self.checkAll_btn)
        self.unckeckAll_btn = QtWidgets.QPushButton(self.ext_grp)
        self.unckeckAll_btn.setMaximumSize(QtCore.QSize(16777215, 17))
        self.unckeckAll_btn.setText("")
        self.unckeckAll_btn.setObjectName("unckeckAll_btn")
        self.horizontalLayout_6.addWidget(self.unckeckAll_btn)
        self.delExt_btn = QtWidgets.QPushButton(self.ext_grp)
        self.delExt_btn.setMinimumSize(QtCore.QSize(0, 15))
        self.delExt_btn.setMaximumSize(QtCore.QSize(16777215, 17))
        self.delExt_btn.setObjectName("delExt_btn")
        self.horizontalLayout_6.addWidget(self.delExt_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addWidget(self.ext_grp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.progress_bar = QtWidgets.QProgressBar(self.centralwidget)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.horizontalLayout_7.addWidget(self.progress_bar)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout_7.addWidget(self.stop_btn)
        self.help_btn = QtWidgets.QPushButton(self.centralwidget)
        self.help_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.help_btn.setMaximumSize(QtCore.QSize(20, 20))
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout_7.addWidget(self.help_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        ratWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(ratWindow)
        self.statusBar.setObjectName("statusBar")
        ratWindow.setStatusBar(self.statusBar)

        self.retranslateUi(ratWindow)
        QtCore.QMetaObject.connectSlotsByName(ratWindow)
        ratWindow.setTabOrder(self.newExt_le, self.over_rb)
        ratWindow.setTabOrder(self.over_rb, self.skip_rb)
        ratWindow.setTabOrder(self.skip_rb, self.ask_rb)
        ratWindow.setTabOrder(self.ask_rb, self.browsIconvert_btn)
        ratWindow.setTabOrder(self.browsIconvert_btn, self.browseTarget_btn)
        ratWindow.setTabOrder(self.browseTarget_btn, self.scrollArea)
        ratWindow.setTabOrder(self.scrollArea, self.extList_lw)
        ratWindow.setTabOrder(self.extList_lw, self.checkAll_btn)
        ratWindow.setTabOrder(self.checkAll_btn, self.unckeckAll_btn)
        ratWindow.setTabOrder(self.unckeckAll_btn, self.delExt_btn)
        ratWindow.setTabOrder(self.delExt_btn, self.stop_btn)
        ratWindow.setTabOrder(self.stop_btn, self.help_btn)
        ratWindow.setTabOrder(self.help_btn, self.RAT_btn)

    def retranslateUi(self, ratWindow):
        ratWindow.setWindowTitle(QtWidgets.QApplication.translate("ratWindow", "MainWindow", None, -1))
        self.iconvertgrp.setTitle(QtWidgets.QApplication.translate("ratWindow", "iConvert", None, -1))
        self.iconvert_lb.setText(QtWidgets.QApplication.translate("ratWindow", "Path", None, -1))
        self.browsIconvert_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Select iconvert dinary", None, -1))
        self.browsIconvert_btn.setText(QtWidgets.QApplication.translate("ratWindow", "...", None, -1))
        self.path_grp.setTitle(QtWidgets.QApplication.translate("ratWindow", "Source dir or files", None, -1))
        self.sub_cb.setText(QtWidgets.QApplication.translate("ratWindow", "Include subfolder", None, -1))
        self.browseFolder_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Select folder to convert", None, -1))
        self.browseFolder_btn.setText(QtWidgets.QApplication.translate("ratWindow", "...", None, -1))
        self.browseFiles_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Select files to convert</span></p></body></html>", None, -1))
        self.browseFiles_btn.setText(QtWidgets.QApplication.translate("ratWindow", "...", None, -1))
        self.remove_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Remove line</span></p></body></html>", None, -1))
        self.remove_btn.setText(QtWidgets.QApplication.translate("ratWindow", "...", None, -1))
        self.show_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Show\\hide full path</span></p></body></html>", None, -1))
        self.show_btn.setText(QtWidgets.QApplication.translate("ratWindow", "...", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("ratWindow", "Out dir", None, -1))
        self.browseTarget_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Select output folder", None, -1))
        self.browseTarget_btn.setText(QtWidgets.QApplication.translate("ratWindow", "...", None, -1))
        self.over_rb.setText(QtWidgets.QApplication.translate("ratWindow", "replace", None, -1))
        self.skip_rb.setText(QtWidgets.QApplication.translate("ratWindow", "skip", None, -1))
        self.ask_rb.setText(QtWidgets.QApplication.translate("ratWindow", "ask", None, -1))
        self.autoRename_rb.setText(QtWidgets.QApplication.translate("ratWindow", "auto", None, -1))
        self.target_le.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Leave empty to use the original folder", None, -1))
        self.RAT_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Start Convert", None, -1))
        self.RAT_btn.setText(QtWidgets.QApplication.translate("ratWindow", "START !!!", None, -1))
        self.multi_cb.setText(QtWidgets.QApplication.translate("ratWindow", "MT", None, -1))
        self.ext_grp.setTitle(QtWidgets.QApplication.translate("ratWindow", "   Ext list", None, -1))
        self.newExt_le.setToolTip(QtWidgets.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter extension and press Return</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">For example:<span style=\" font-weight:600;\"> jpg</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">If extension already exists, text ignored</span></p></body></html>", None, -1))
        self.extList_lw.setToolTip(QtWidgets.QApplication.translate("ratWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Uncheck for skip file type</p></body></html>", None, -1))
        self.checkAll_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Select all", None, -1))
        self.checkAll_btn.setText(QtWidgets.QApplication.translate("ratWindow", "v", None, -1))
        self.unckeckAll_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Unselect all", None, -1))
        self.delExt_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Delete Ext", None, -1))
        self.delExt_btn.setText(QtWidgets.QApplication.translate("ratWindow", "-", None, -1))
        self.stop_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Stop process", None, -1))
        self.stop_btn.setText(QtWidgets.QApplication.translate("ratWindow", "STOP", None, -1))
        self.help_btn.setToolTip(QtWidgets.QApplication.translate("ratWindow", "Show help", None, -1))
        self.help_btn.setText(QtWidgets.QApplication.translate("ratWindow", "?", None, -1))

